### ISSUE TITLE
Error creating Data-Contract

### ISSUE THREAD

**Issue by readme55** [dashevo/DashJS#94]
Cannot create data-contract tested https://dashplatform.readme.io/docs/tutorial-register-a-data-contract using node and also dash.min.js
Using Windows 10 and node/npm version listed below. @dashameter confirmed on discord he can register data-contract successfully on Linux!

## Current Behavior
error in node (const Dash = require('dash');):
```
Something went wrong: Invalid Argument: Expect signers to be a hex string
Error
    at new NodeError (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\errors\index.js:23:41)
    at Object.checkArgument (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\util\preconditions.js:17:13)
    at QuorumEntry.validate (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\QuorumEntry.js:194:5)
    at Function.fromObject (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\QuorumEntry.js:186:18)
    at new QuorumEntry (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\QuorumEntry.js:60:26)
    at C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\SimplifiedMNLisreadmeiff.js:172:12
    at Array.map (<anonymous>)
    at Function.fromObject (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\SimplifiedMNLisreadmeiff.js:171:52)
    at new SimplifiedMNLisreadmeiff (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\SimplifiedMNLisreadmeiff.js:39:35)
    at SimplifiedMNList.applyDiff (C:\Users\readme\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dashcore-lib\lib\deterministicmnlist\SimplifiedMNList.js:50:14) {
  message: 'Invalid Argument: Expect signers to be a hex string',
  stack: 'Invalid Argument: Expect signers to be a hex string\n' +
```

Error with dash.min.js (// const Dash = require('./lib/dash.min.js');):
```
Something went wrong: TypeError: (e.adapter || a.adapter) is not a function
    at e.exports (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:697340)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.request (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:694815)
    at async e.exports.makeRequest (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:24:563883)
    at async e.exports.updateMNList (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:701760)
    at async e.exports.getMNList (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:702707)
    at async e.exports.getRandomMasternode (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:702909)
    at async e.exports.getGrpcUrl (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:704245)
    at async e.exports.makeRequest (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:703905)
    at async e.exports.getIdentity (C:\Users\readme\myProjects\Projects\evonet\lib\dash.min.js:31:576380)
```

## Steps to Reproduce (for bugs)
Run the example with node  https://dashplatform.readme.io/docs/tutorial-register-a-data-contract

## Your Environment

* Version used: DashJS 3.13.3
npm 6.14.4
node v12.16.2

* Operating System and version (desktop, server, or mobile): Windows10

**Comment by thephez** [comment]
I can confirm that I have issues too. v3.13.2 worked for me, but I just started getting errors when I updated to v3.13.3. Looks like it may be related to recent dashcore-lib changes? Maybe dashevo/dashcore-lib#153?

**Comment by thephez** [comment]
Related to dashevo/dashcore-lib#159

**Comment by readme55** [comment]
all working again. I close the issue. thx!
